# Generated by Django 4.2.6 on 2023-11-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='is_passed',
            field=models.BooleanField(null=True),
        ),
    ]
