# Generated by Django 4.2.6 on 2023-11-04 22:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationLinks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('group_name', models.CharField(max_length=50)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='admingroup',
            name='key',
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='key',
        ),
        migrations.RemoveField(
            model_name='tutorgroup',
            name='key',
        ),
    ]
