# Generated by Django 4.2.6 on 2023-11-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='header',
            field=models.CharField(max_length=80),
        ),
    ]
