# Generated by Django 4.2.6 on 2023-11-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationlinks',
            name='group_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
