# Generated by Django 4.2.6 on 2023-11-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('file', models.FileField(upload_to='student_files/')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='creator',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.ManyToManyField(to='main.studentfile'),
        ),
    ]
