# Generated by Django 4.2.6 on 2023-12-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='users_id',
            new_name='groups_id',
        ),
    ]
