# Generated by Django 4.2.6 on 2023-11-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_studentfile_subject_creator_task_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='files',
        ),
    ]
