# Generated by Django 4.2.6 on 2023-11-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_is_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ffdfdf', models.CharField(max_length=40)),
            ],
        ),
    ]
