# Generated by Django 4.2.6 on 2023-11-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usertask_is_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='is_passed',
            field=models.BooleanField(default=0),
        ),
    ]
