# Generated by Django 4.2.6 on 2023-11-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_registrationlinks_remove_admingroup_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admingroup',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tutorgroup',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
