# Generated by Django 4.2.6 on 2023-12-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_users_id_subject_groups_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='groups_id',
            new_name='enrolled_student_group',
        ),
    ]
