# Generated by Django 4.2.6 on 2023-11-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_usertask_is_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='is_passed',
        ),
    ]
