# Generated by Django 4.2.6 on 2023-11-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mama'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MAMA',
        ),
        migrations.AddField(
            model_name='notification',
            name='ffdfdf',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
