# Generated by Django 4.2.3 on 2023-08-28 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
