# Generated by Django 4.2.6 on 2023-12-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_groups_id_subject_enrolled_student_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='enrolled_student_group',
            new_name='enrolled_groups_id',
        ),
    ]
