# Generated by Django 4.2.6 on 2023-11-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_usertask_is_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='group_id',
        ),
    ]
