# Generated by Django 4.2.6 on 2023-11-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_mama_notification_ffdfdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='ffdfdf',
        ),
    ]
