# Generated by Django 4.2.6 on 2023-11-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_notification_ffdfdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='checker_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='own_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
