# Generated by Django 3.1.1 on 2023-10-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20231013_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papa', models.CharField(max_length=234)),
            ],
            options={
                'verbose_name': 'Папа',
                'verbose_name_plural': 'Папы',
            },
        ),
    ]
