# Generated by Django 4.2.6 on 2023-11-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_usertask_checker_grade_usertask_own_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='name_task',
        ),
        migrations.AlterField(
            model_name='usertask',
            name='time_delivery',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
