# Generated by Django 3.1.1 on 2023-10-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_papa'),
    ]

    operations = [
        migrations.AddField(
            model_name='papa',
            name='mama',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
