# Generated by Django 4.2.6 on 2023-11-23 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_usertask_name_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='file_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.studentfile'),
        ),
    ]
