# Generated by Django 4.2.6 on 2023-11-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_subject_groups_name_subject_tutor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='groups_name',
            new_name='user_id',
        ),
    ]
