# Generated by Django 4.2.6 on 2023-11-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_usertask_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='group_id',
        ),
        migrations.AddField(
            model_name='usertask',
            name='file_list_id',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
