# Generated by Django 4.2.6 on 2023-11-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_usertask_file_id_remove_usertask_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.studentgroup'),
        ),
    ]
