# Generated by Django 4.2.6 on 2023-10-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_study_group_user_studygroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='studyGroup',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='key',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
