# Generated by Django 4.2.6 on 2023-11-18 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_user_id_subject_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.subject'),
        ),
    ]
