# Generated by Django 4.2.6 on 2023-10-27 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_teacherassign'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_task', models.CharField(max_length=256)),
                ('grade', models.IntegerField()),
                ('time_delivery', models.DateTimeField()),
                ('main_task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
