# Generated by Django 4.2.6 on 2023-10-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_admingroup_teachergroup_remove_user_studygroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
