# Generated by Django 4.2.6 on 2023-11-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_task_subject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subject_id',
        ),
    ]
