# Generated by Django 4.2.6 on 2023-10-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_studentgroup_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admingroup',
            name='key',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachergroup',
            name='key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
