# Generated by Django 4.2.6 on 2023-11-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_usertask_name_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='name_task',
        ),
    ]
