# Generated by Django 4.2.6 on 2023-10-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_admingroup_key_alter_teachergroup_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherGroup',
            new_name='TutorGroup',
        ),
    ]
