# Generated by Django 4.2.6 on 2023-10-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_usertask_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.studentgroup'),
        ),
    ]
