# Generated by Django 4.2.6 on 2023-11-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_usertask_name_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='checker_grade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='grade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='own_grade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
