# Generated by Django 4.2.6 on 2023-11-24 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_usertask_file_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcheck',
            name='main_task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.task'),
        ),
        migrations.AlterField(
            model_name='groupcheck',
            name='usser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
