# Generated by Django 4.2.6 on 2023-10-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_groupcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcheck',
            name='usser_id',
            field=models.IntegerField(null=True),
        ),
    ]
