# Generated by Django 4.2.6 on 2023-10-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_groupcheck_usser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='first_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='last_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
