# Generated by Django 4.2.6 on 2023-10-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_usertask_first_name_usertask_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='last_name',
        ),
    ]
