# Generated by Django 4.2.6 on 2023-10-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_usertask_first_name_usertask_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='time_delivery',
            field=models.DateTimeField(null=True),
        ),
    ]
