# Generated by Django 4.2.6 on 2023-10-29 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_usertask_time_delivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAssign',
        ),
    ]
