# Generated by Django 4.2.6 on 2023-10-31 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_delete_teacherassign'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcheck',
            name='main_task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.task'),
        ),
    ]
