# Generated by Django 4.2.6 on 2023-10-31 15:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_groupcheck_main_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcheck',
            name='user_check_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
