# Generated by Django 4.2.6 on 2023-10-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_groupcheck_user_check_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcheck',
            name='main_task_id',
            field=models.IntegerField(null=True),
        ),
    ]
