# Generated by Django 4.2.6 on 2023-10-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_groupcheck_main_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcheck',
            name='user_check_id',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
